name: Terraform Plan

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      AWS_REGION: 'us-east-1'
      AWS_PROFILE: 'default'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: S3 List
      run: |
        aws s3 ls --profile default
