name: Terraform Plan

on:
  push:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2 
    - name: S3 List
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        echo "AWS_PROFILE=default" >> $GITHUB_ENV
        cat $GITHUB_ENV
        aws configure set aws_access_key_id ${{ secrets.ACCESS_KEY }}
        aws configure set aws_secret_access_key 12
        aws configure set default.region us-east-1
        aws configure set default.profile default

        aws s3 ls --profile default
